In [1]:
import pandas as pd

In [2]:
# data_tool은 장부작석용
# test_data_tool은 패널 작업용 (기존의 df)

data_tool = pd.read_excel("/Users/yshmbid/Documents/home/github/kosmos/workspace/data/20260512_Data tool_20260512082456636.xlsx", engine="openpyxl")
test_data_tool = pd.read_csv("/Users/yshmbid/Documents/home/github/kosmos/workspace/data/datatool.csv")

/opt/anaconda3/envs/skala/lib/python3.11/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [3]:
data_tool

,LOCATION_NAME,SUBJ_ID,VISIT_NM,CRF_NM,NGS_FILE,COMN_NM
0,가천대길병원,S023-014,결과,NGS,S023_014_gain.vcf,Oncomine
1,가천대길병원,S023-013,결과,NGS,S023_013_gainloss.vcf,GIL-ONCOaccuPanel(NGeneBio) v1.4
2,가천대길병원,S023-012,결과,NGS,S023_012_snvindelgainloss.vcf,GIL-ONCOaccuPanel(NGeneBio) v1.4
3,가천대길병원,S023-011,결과,NGS,S023_011_gainloss.vcf,GIL-ONCOaccuPanel(NGeneBio) v1.4
4,가천대길병원,S023-010,결과,NGS,S023_010_snvindel.vcf,GIL-ONCOaccuPanel(NGeneBio) v1.4
...,...,...,...,...,...,...
986,화순전남대학교병원,S031-005,결과,NGS,S031-005 NGS-1225-22_final.vcf,ONCOaccupanel DNA
987,화순전남대학교병원,S031-004,결과,NGS,S031-004 NGS-1355-22_final.vcf,ONCOaccupanel DNA
988,화순전남대학교병원,S031-003,결과,NGS,S08857_S08857T1_D1_KM_v1.2_DP0401-MBQ20.vcf,CancerSCAN v3.1
989,화순전남대학교병원,S031-002,결과,NGS,S031-002 NGS-1265-22_final.vcf,ONCOaccupanel DNA
990,화순전남대학교병원,S031-001,결과,NGS,NGS-1222-22_final.vcf,ONCOaccupanel DNA

In [4]:
test_data_tool

,HOSP_ID,SUBJ_ID,BRND_CD,BRND_NM_VER,BRND_NM_ECT_YN,BRND_NM_ECT_CMNT,hosp_brnd_cd,ecrf_annot,panel_annot,exist_in_maf
0,S001,S001-001,P008,Oncomine Comprehensive Assay v3,NaN,NaN,S001_P008,y,y,n
1,S001,S001-090,P016,TSO500 ver2.2,NaN,NaN,S001_P016,y,y,y
2,S001,S001-089,P016,TSO500 ver2.2,NaN,NaN,S001_P016,y,y,y
3,S001,S001-087,P016,TSO500 ver2.2,NaN,NaN,S001_P016,y,y,y
4,S001,S001-086,P016,TSO500 ver2.2,NaN,NaN,S001_P016,y,y,y
...,...,...,...,...,...,...,...,...,...,...
1002,S031,S031-006,P018,ONCOaccuPanel v4.3,NaN,NaN,S031_P018,y,y,y
1003,S032,S032-002,P019,ONCOaccuPanel v4.5,NaN,NaN,S032_P019,y,n,y
1004,S032,S032-003,P016,TSO500 ver2.2,NaN,NaN,S032_P016,y,n,y
1005,S032,S032-004,NaN,NaN,1.0,S032-004_panel(AUH-SCT1?),NaN,n,n,y
1006,S032,S032-005,P007,Oncomine Comprehensive Assay Plus,NaN,NaN,S032_P007,y,n,y

In [5]:
panel_table_path = "/Users/yshmbid/Documents/home/github/kosmos/workspace/data/sheet3.csv"
txt_path = "/Users/yshmbid/Documents/home/github/kosmos/workspace/data/maf_files_0430.txt"

panel_table = pd.read_csv(panel_table_path)

with open(txt_path, "r", encoding="utf-8") as f:
    maf_files = [line.strip() for line in f if line.strip()]

maf_df = pd.DataFrame({
    "HOSP_ID": [file_name[:4] for file_name in maf_files],
    "file_name": maf_files
})

In [6]:
panel_table

   panel_cd                             panel_nm site_cd     site_nm
0      P001                  AlphaLiquid®100(v2)    S003      고대안암병원
1      P001                  AlphaLiquid®100(v2)    S016  고려대학교 구로병원
2      P001                  AlphaLiquid®100(v2)    S017     계명대동산병원
3      P001                  AlphaLiquid®100(v2)    S012      서울성모병원
4      P002                             AUH-SCT1    S011       아주대병원
..      ...                                  ...     ...         ...
87     P034                      CancerSCAN v3.1    S009      강북삼성병원
88     P034                      CancerSCAN v3.1    S025       분당차병원
89     P034                      CancerSCAN v3.1    S031   화순전남대학교병원
90     P035               KUMC cancer Panel v1.1    S003      고대안암병원
91     P036  CancerScan IO+P & CancerSCAN RNA FE    S012      서울성모병원

[92 rows x 4 columns]

In [7]:
maf_df

    HOSP_ID                    file_name
0      S001                 S001-002.maf
1      S001                 S001-004.maf
2      S001                 S001-005.maf
3      S001                 S001-006.maf
4      S001                 S001-007.maf
..      ...                          ...
923    S032                 S032-001.maf
924    S032                 S032-002.maf
925    S032                 S032-003.maf
926    S032                 S032-004.maf
927    S032  S032-005_20251113-18055.maf

[928 rows x 2 columns]

In [8]:
panel_table['hosp_brnd_cd'] = panel_table['site_cd'] + '_' + panel_table['panel_cd']

In [9]:
panel_table

,panel_cd,panel_nm,site_cd,site_nm,hosp_brnd_cd
0,P001,AlphaLiquid®100(v2),S003,고대안암병원,S003_P001
1,P001,AlphaLiquid®100(v2),S016,고려대학교 구로병원,S016_P001
2,P001,AlphaLiquid®100(v2),S017,계명대동산병원,S017_P001
3,P001,AlphaLiquid®100(v2),S012,서울성모병원,S012_P001
4,P002,AUH-SCT1,S011,아주대병원,S011_P002
...,...,...,...,...,...
87,P034,CancerSCAN v3.1,S009,강북삼성병원,S009_P034
88,P034,CancerSCAN v3.1,S025,분당차병원,S025_P034
89,P034,CancerSCAN v3.1,S031,화순전남대학교병원,S031_P034
90,P035,KUMC cancer Panel v1.1,S003,고대안암병원,S003_P035
91,P036,CancerScan IO+P & CancerSCAN RNA FE,S012,서울성모병원,S012_P036

In [10]:
maf_df["SUBJ_ID"] = maf_df["file_name"].astype(str).str[:8]

In [11]:
maf_df

    HOSP_ID                    file_name   SUBJ_ID
0      S001                 S001-002.maf  S001-002
1      S001                 S001-004.maf  S001-004
2      S001                 S001-005.maf  S001-005
3      S001                 S001-006.maf  S001-006
4      S001                 S001-007.maf  S001-007
..      ...                          ...       ...
923    S032                 S032-001.maf  S032-001
924    S032                 S032-002.maf  S032-002
925    S032                 S032-003.maf  S032-003
926    S032                 S032-004.maf  S032-004
927    S032  S032-005_20251113-18055.maf  S032-005

[928 rows x 3 columns]

In [12]:
maf_df['SUBJ_ID'] = maf_df['SUBJ_ID'].str.replace(r'(S\d{3})_(\d{3})', r'\1-\2', regex=True)

In [13]:
maf_df

    HOSP_ID                    file_name   SUBJ_ID
0      S001                 S001-002.maf  S001-002
1      S001                 S001-004.maf  S001-004
2      S001                 S001-005.maf  S001-005
3      S001                 S001-006.maf  S001-006
4      S001                 S001-007.maf  S001-007
..      ...                          ...       ...
923    S032                 S032-001.maf  S032-001
924    S032                 S032-002.maf  S032-002
925    S032                 S032-003.maf  S032-003
926    S032                 S032-004.maf  S032-004
927    S032  S032-005_20251113-18055.maf  S032-005

[928 rows x 3 columns]

In [14]:
data = test_data_tool[['HOSP_ID', 'SUBJ_ID', 'BRND_CD']]

In [15]:
data

     HOSP_ID   SUBJ_ID BRND_CD
0       S001  S001-001    P008
1       S001  S001-090    P016
2       S001  S001-089    P016
3       S001  S001-087    P016
4       S001  S001-086    P016
...      ...       ...     ...
1002    S031  S031-006    P018
1003    S032  S032-002    P019
1004    S032  S032-003    P016
1005    S032  S032-004     NaN
1006    S032  S032-005    P007

[1007 rows x 3 columns]

In [16]:
maf_df['BRND_CD_RAW'] = maf_df['SUBJ_ID'].apply(
    lambda cur_sid: data.loc[(data['SUBJ_ID'] == cur_sid) & (data['BRND_CD'].notna()), 'BRND_CD'].tolist()
)

In [17]:
maf_df

    HOSP_ID                    file_name   SUBJ_ID BRND_CD_RAW
0      S001                 S001-002.maf  S001-002      [P016]
1      S001                 S001-004.maf  S001-004      [P016]
2      S001                 S001-005.maf  S001-005      [P016]
3      S001                 S001-006.maf  S001-006      [P012]
4      S001                 S001-007.maf  S001-007      [P016]
..      ...                          ...       ...         ...
923    S032                 S032-001.maf  S032-001          []
924    S032                 S032-002.maf  S032-002      [P019]
925    S032                 S032-003.maf  S032-003      [P016]
926    S032                 S032-004.maf  S032-004          []
927    S032  S032-005_20251113-18055.maf  S032-005      [P007]

[928 rows x 4 columns]

In [18]:
maf_df[maf_df['BRND_CD_RAW'].apply(len) == 0]

    HOSP_ID                      file_name   SUBJ_ID BRND_CD_RAW
54     S001                   S001-062.maf  S001-062          []
60     S001                   S001-068.maf  S001-068          []
66     S001                   S001-074.maf  S001-074          []
74     S001                   S001-082.maf  S001-082          []
80     S001                   S001-088.maf  S001-088          []
..      ...                            ...       ...         ...
910    S031                   S031-012.maf  S031-012          []
917    S031                   S031-023.maf  S031-023          []
919    S031  S031-025 NGS-391-23-final.maf  S031-025          []
923    S032                   S032-001.maf  S032-001          []
926    S032                   S032-004.maf  S032-004          []

[102 rows x 4 columns]

In [19]:
maf_df[maf_df['BRND_CD_RAW'].apply(len) >= 2]

    HOSP_ID                file_name   SUBJ_ID         BRND_CD_RAW
26     S001             S001-031.maf  S001-031        [P016, P004]
49     S001             S001-057.maf  S001-057        [P016, P016]
187    S003    S003-046-snvindel.maf  S003-046        [P034, P001]
219    S003         S003-066-CNV.maf  S003-066        [P001, P016]
220    S003         S003-066-SNV.maf  S003-066        [P001, P016]
228    S003             S003-075.maf  S003-075        [P001, P034]
233    S003             S003-078.maf  S003-078        [P034, P001]
268    S003             S003-904.maf  S003-904        [P034, P034]
270    S004             S004-002.maf  S004-002  [P017, P028, P028]
274    S004             S004-005.maf  S004-005        [P016, P005]
283    S004             S004-010.maf  S004-010        [P016, P005]
475    S007    S007-001-snvindel.maf  S007-001        [P007, P007]
476    S007    S007-002-snvindel.maf  S007-002        [P007, P007]
477    S007    S007-003-snvindel.maf  S007-003        [P007, P007]
478    S007    S007-004-snvindel.maf  S007-004        [P007, P007]
479    S007    S007-005-snvindel.maf  S007-005        [P007, P007]
480    S007    S007-006-snvindel.maf  S007-006        [P007, P007]
481    S007    S007-007-snvindel.maf  S007-007        [P007, P007]
482    S007    S007-008-snvindel.maf  S007-008        [P007, P007]
483    S007    S007-009-snvindel.maf  S007-009        [P007, P007]
484    S007    S007-010-snvindel.maf  S007-010        [P007, P007]
485    S007    S007-011-snvindel.maf  S007-011        [P007, P007]
486    S007    S007-012-snvindel.maf  S007-012        [P007, P007]
487    S007    S007-013-snvindel.maf  S007-013        [P007, P007]
490    S007             S007-016.maf  S007-016        [P007, P031]
495    S007             S007-022.maf  S007-022        [P007, P007]
521    S009             S009-007.maf  S009-007        [P034, P034]
522    S009  S009-008-CancerScan.maf  S009-008        [P034, P003]
523    S009        S009-008-KM12.maf  S009-008        [P034, P003]
616    S011             S011-001.maf  S011-001        [P016, P004]
620    S011             S011-005.maf  S011-005        [P016, P016]
652    S012             S012-011.maf  S012-011        [P007, P007]
661    S012             S012-021.maf  S012-021        [P007, P036]
707    S014             S014-002.maf  S014-002        [P014, P014]
716    S014          S014-011VCF.maf  S014-011        [P024, P024]
813    S022             S022-001.maf  S022-001  [P013, P013, P013]
814    S022             S022-002.maf  S022-002        [P013, P013]
833    S024    S024-005-snvindel.maf  S024-005        [P018, P004]
857    S026             S026-001.maf  S026-001        [P007, P007]
869    S027             S027-006.maf  S027-006        [P007, P007]
870    S027             S027-007.maf  S027-007        [P007, P007]
875    S027             S027-012.maf  S027-012        [P007, P007]
895    S030             S030-004.maf  S030-004        [P007, P007]
896    S030             S030-005.maf  S030-005        [P007, P007]
897    S030             S030-006.maf  S030-006        [P008, P008]
898    S030             S030-007.maf  S030-007        [P007, P007]

In [20]:
data[data['SUBJ_ID'] == 'S022-001']

    HOSP_ID   SUBJ_ID BRND_CD
866    S022  S022-001    P013
867    S022  S022-001    P013
868    S022  S022-001    P013

In [21]:
data

     HOSP_ID   SUBJ_ID BRND_CD
0       S001  S001-001    P008
1       S001  S001-090    P016
2       S001  S001-089    P016
3       S001  S001-087    P016
4       S001  S001-086    P016
...      ...       ...     ...
1002    S031  S031-006    P018
1003    S032  S032-002    P019
1004    S032  S032-003    P016
1005    S032  S032-004     NaN
1006    S032  S032-005    P007

[1007 rows x 3 columns]

In [22]:
test_data_tool[test_data_tool['SUBJ_ID'] == 'S022-001']

,HOSP_ID,SUBJ_ID,BRND_CD,BRND_NM_VER,BRND_NM_ECT_YN,BRND_NM_ECT_CMNT,hosp_brnd_cd,ecrf_annot,panel_annot,exist_in_maf
866,S022,S022-001,P013,Solid Tumor Panel II(TMB/MSI)(RNA included),NaN,NaN,S022_P013,y,y,y
867,S022,S022-001,P013,NaN,1.0,Solid Tumor Panel II(TMB/MSI)(RNA included),S022_P013,y,y,y
868,S022,S022-001,P013,Solid Tumor Panel II(TMB/MSI)(RNA included),NaN,NaN,S022_P013,y,y,y

In [27]:
import numpy as np

maf_df['BRND_CD'] = maf_df['BRND_CD_RAW'].apply(lambda x: x[0] if len(x) == 1 else np.nan)

In [28]:
maf_df

    HOSP_ID                    file_name   SUBJ_ID BRND_CD_RAW BRND_CD
0      S001                 S001-002.maf  S001-002      [P016]    P016
1      S001                 S001-004.maf  S001-004      [P016]    P016
2      S001                 S001-005.maf  S001-005      [P016]    P016
3      S001                 S001-006.maf  S001-006      [P012]    P012
4      S001                 S001-007.maf  S001-007      [P016]    P016
..      ...                          ...       ...         ...     ...
923    S032                 S032-001.maf  S032-001          []     NaN
924    S032                 S032-002.maf  S032-002      [P019]    P019
925    S032                 S032-003.maf  S032-003      [P016]    P016
926    S032                 S032-004.maf  S032-004          []     NaN
927    S032  S032-005_20251113-18055.maf  S032-005      [P007]    P007

[928 rows x 5 columns]

In [30]:
maf_df.to_csv("/Users/yshmbid/Documents/home/github/kosmos/workspace/data/maf_0512.csv", index=False)

In [31]:
maf_for_check = maf_df[maf_df['BRND_CD_RAW'].apply(len) >= 2]

In [34]:
maf_df

    HOSP_ID                    file_name   SUBJ_ID BRND_CD_RAW BRND_CD
0      S001                 S001-002.maf  S001-002      [P016]    P016
1      S001                 S001-004.maf  S001-004      [P016]    P016
2      S001                 S001-005.maf  S001-005      [P016]    P016
3      S001                 S001-006.maf  S001-006      [P012]    P012
4      S001                 S001-007.maf  S001-007      [P016]    P016
..      ...                          ...       ...         ...     ...
923    S032                 S032-001.maf  S032-001          []     NaN
924    S032                 S032-002.maf  S032-002      [P019]    P019
925    S032                 S032-003.maf  S032-003      [P016]    P016
926    S032                 S032-004.maf  S032-004          []     NaN
927    S032  S032-005_20251113-18055.maf  S032-005      [P007]    P007

[928 rows x 5 columns]

In [35]:
test_data_tool

,HOSP_ID,SUBJ_ID,BRND_CD,BRND_NM_VER,BRND_NM_ECT_YN,BRND_NM_ECT_CMNT,hosp_brnd_cd,ecrf_annot,panel_annot,exist_in_maf
0,S001,S001-001,P008,Oncomine Comprehensive Assay v3,NaN,NaN,S001_P008,y,y,n
1,S001,S001-090,P016,TSO500 ver2.2,NaN,NaN,S001_P016,y,y,y
2,S001,S001-089,P016,TSO500 ver2.2,NaN,NaN,S001_P016,y,y,y
3,S001,S001-087,P016,TSO500 ver2.2,NaN,NaN,S001_P016,y,y,y
4,S001,S001-086,P016,TSO500 ver2.2,NaN,NaN,S001_P016,y,y,y
...,...,...,...,...,...,...,...,...,...,...
1002,S031,S031-006,P018,ONCOaccuPanel v4.3,NaN,NaN,S031_P018,y,y,y
1003,S032,S032-002,P019,ONCOaccuPanel v4.5,NaN,NaN,S032_P019,y,n,y
1004,S032,S032-003,P016,TSO500 ver2.2,NaN,NaN,S032_P016,y,n,y
1005,S032,S032-004,NaN,NaN,1.0,S032-004_panel(AUH-SCT1?),NaN,n,n,y
1006,S032,S032-005,P007,Oncomine Comprehensive Assay Plus,NaN,NaN,S032_P007,y,n,y

In [36]:
maf_df['BRND_NM_ECT_YN'] = np.nan
maf_df['BRND_NM_ECT_CMNT'] = np.nan

for idx in maf_df[maf_df['BRND_CD_RAW'].apply(len) == 0].index:
    cur_sid = maf_df.loc[idx, 'SUBJ_ID']
    cur_df = test_data_tool.loc[test_data_tool['SUBJ_ID'] == cur_sid]
    if not cur_df.empty and cur_df['BRND_NM_ECT_CMNT'].notna().any():
        maf_df.loc[idx, 'BRND_NM_ECT_YN'] = 1
        maf_df.loc[idx, 'BRND_NM_ECT_CMNT'] = cur_df['BRND_NM_ECT_CMNT'].dropna().values[0]

/var/folders/5_/cr0lgx655m7fqg_j4q733qbm0000gn/T/ipykernel_81748/291625199.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'FIRST-Cancer Panel v3.3' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  maf_df.loc[idx, 'BRND_NM_ECT_CMNT'] = cur_df['BRND_NM_ECT_CMNT'].dropna().values[0]

In [37]:
maf_df

,HOSP_ID,file_name,SUBJ_ID,BRND_CD_RAW,BRND_CD,BRND_NM_ECT_YN,BRND_NM_ECT_CMNT
0,S001,S001-002.maf,S001-002,[P016],P016,NaN,NaN
1,S001,S001-004.maf,S001-004,[P016],P016,NaN,NaN
2,S001,S001-005.maf,S001-005,[P016],P016,NaN,NaN
3,S001,S001-006.maf,S001-006,[P012],P012,NaN,NaN
4,S001,S001-007.maf,S001-007,[P016],P016,NaN,NaN
...,...,...,...,...,...,...,...
923,S032,S032-001.maf,S032-001,[],NaN,NaN,NaN
924,S032,S032-002.maf,S032-002,[P019],P019,NaN,NaN
925,S032,S032-003.maf,S032-003,[P016],P016,NaN,NaN
926,S032,S032-004.maf,S032-004,[],NaN,1.0,S032-004_panel(AUH-SCT1?)
927,S032,S032-005_20251113-18055.maf,S032-005,[P007],P007,NaN,NaN

In [ ]:
maf_df[(maf_df['BRND_CD_RAW'].apply(len) == 0) & (maf_df['BRND_NM_ECT_CMNT'].isna())]

,HOSP_ID,file_name,SUBJ_ID,BRND_CD_RAW,BRND_CD,BRND_NM_ECT_YN,BRND_NM_ECT_CMNT
54,S001,S001-062.maf,S001-062,[],NaN,NaN,NaN
60,S001,S001-068.maf,S001-068,[],NaN,NaN,NaN
66,S001,S001-074.maf,S001-074,[],NaN,NaN,NaN
74,S001,S001-082.maf,S001-082,[],NaN,NaN,NaN
80,S001,S001-088.maf,S001-088,[],NaN,NaN,NaN
84,S001,S001-092.maf,S001-092,[],NaN,NaN,NaN
118,S002,S002-028.maf,S002-028,[],NaN,NaN,NaN
119,S002,S002-029.maf,S002-029,[],NaN,NaN,NaN
122,S002,S002-032.maf,S002-032,[],NaN,NaN,NaN
123,S002,S002-033.maf,S002-033,[],NaN,NaN,NaN
161,S003,S003-019.maf,S003-019,[],NaN,NaN,NaN
193,S003,S003-051-cnv.maf,S003-051,[],NaN,NaN,NaN
194,S003,S003-051-snv.maf,S003-051,[],NaN,NaN,NaN
326,S004,S004-044-pm.maf,S004-044,[],NaN,NaN,NaN
327,S004,S004-044-sv.maf,S004-044,[],NaN,NaN,NaN
384,S006,S006-024.maf,S006-024,[],NaN,NaN,NaN
442,S006,S006-084.maf,S006-084,[],NaN,NaN,NaN
460,S006,S006-102.maf,S006-102,[],NaN,NaN,NaN
469,S006,S006-111.maf,S006-111,[],NaN,NaN,NaN
497,S007,S007-024.maf,S007-024,[],NaN,NaN,NaN
508,S008,S008-011.maf,S008-011,[],NaN,NaN,NaN
511,S008,S008-015.maf,S008-015,[],NaN,NaN,NaN
565,S010,S010-039.maf,S010-039,[],NaN,NaN,NaN
588,S010,S010-063.maf,S010-063,[],NaN,NaN,NaN
598,S010,S010-073.maf,S010-073,[],NaN,NaN,NaN
625,S011,S011-011.maf,S011-011,[],NaN,NaN,NaN
627,S011,S011-013.maf,S011-013,[],NaN,NaN,NaN
662,S012,S012-022.maf,S012-022,[],NaN,NaN,NaN
666,S012,S012-026.maf,S012-026,[],NaN,NaN,NaN
676,S012,S012-037_S012-037_vcf.maf,S012-037,[],NaN,NaN,NaN
706,S014,S014-001.maf,S014-001,[],NaN,NaN,NaN
778,S018,S018-022_M25-007727_dna.cnv.maf,S018-022,[],NaN,NaN,NaN
779,S018,S018-022_M25-007727_dna.hard-filtered.maf,S018-022,[],NaN,NaN,NaN
780,S018,S018-022_M25-007727_dna_DragenExonCNV.maf,S018-022,[],NaN,NaN,NaN
781,S018,S018-022_M25-007727_rna_SpliceVariants.maf,S018-022,[],NaN,NaN,NaN
825,S023,S023-011.maf,S023-011,[],NaN,NaN,NaN
834,S024,S024-006-snvindel.maf,S024-006,[],NaN,NaN,NaN
877,S027,S027-014.maf,S027-014,[],NaN,NaN,NaN
910,S031,S031-012.maf,S031-012,[],NaN,NaN,NaN
919,S031,S031-025 NGS-391-23-final.maf,S031-025,[],NaN,NaN,NaN
923,S032,S032-001.maf,S032-001,[],NaN,NaN,NaN

In [40]:
maf_df.to_csv("/Users/yshmbid/Documents/home/github/kosmos/workspace/data/maf_0512_v2.csv", index=False)

In [41]:
panel_500 = pd.read_excel("/Users/yshmbid/Documents/home/github/kosmos/workspace/data/510명 대상자 패널 정보.xlsx", engine="openpyxl")

In [43]:
panel_500 = panel_500[['SUBJ_ID', 'BRND_CD']]

In [44]:
panel_500

      SUBJ_ID BRND_CD
0    S001-002    P016
1    S001-004    P016
2    S001-005    P016
3    S001-006    P012
4    S001-007    P016
..        ...     ...
923       NaN     NaN
924       NaN     NaN
925       NaN     NaN
926       NaN     NaN
927       NaN     NaN

[928 rows x 2 columns]

In [46]:
maf_df = maf_df[['SUBJ_ID', 'BRND_CD']]

In [47]:
maf_df

      SUBJ_ID BRND_CD
0    S001-002    P016
1    S001-004    P016
2    S001-005    P016
3    S001-006    P012
4    S001-007    P016
..        ...     ...
923  S032-001     NaN
924  S032-002    P019
925  S032-003    P016
926  S032-004     NaN
927  S032-005    P007

[928 rows x 2 columns]

In [63]:
panel_500 = panel_500.dropna(how='all')
maf_df = maf_df.drop_duplicates(subset='SUBJ_ID', keep='first')
maf_df = maf_df.dropna(subset=['BRND_CD'])

In [64]:
panel_500

      SUBJ_ID BRND_CD
0    S001-002    P016
1    S001-004    P016
2    S001-005    P016
3    S001-006    P012
4    S001-007    P016
..        ...     ...
505  S031-007    P018
506  S031-008    P018
507  S031-010    P018
508  S031-011    P018
509  S031-015    P018

[510 rows x 2 columns]

In [65]:
maf_df

      SUBJ_ID BRND_CD
0    S001-002    P016
1    S001-004    P016
2    S001-005    P016
3    S001-006    P012
4    S001-007    P016
..        ...     ...
921  S031-028    P018
922  S031-029    P018
924  S032-002    P019
925  S032-003    P016
927  S032-005    P007

[716 rows x 2 columns]

In [66]:
merged_df = pd.merge(panel_500, maf_df, on='SUBJ_ID', how='right', suffixes=('', '_panel'))

In [67]:
merged_df

      SUBJ_ID BRND_CD BRND_CD_panel
0    S001-002    P016          P016
1    S001-004    P016          P016
2    S001-005    P016          P016
3    S001-006    P012          P012
4    S001-007    P016          P016
..        ...     ...           ...
711  S031-028     NaN          P018
712  S031-029     NaN          P018
713  S032-002     NaN          P019
714  S032-003     NaN          P016
715  S032-005     NaN          P007

[716 rows x 3 columns]

In [71]:
existing_brnd = merged_df['BRND_CD'].dropna().unique()
not_in_500 = merged_df.loc[
    merged_df['BRND_CD'].isna() & merged_df['BRND_CD_panel'].notna(),
    'BRND_CD_panel'
].unique()
not_in_500 = [x for x in not_in_500 if x not in existing_brnd]
not_in_500

['P021',
 'P035',
 'P034',
 'P033',
 'P025',
 'P032',
 'P003',
 'P036',
 'P002',
 'P014',
 'P031',
 'P030']

In [72]:
merged_df[merged_df['BRND_CD_panel'].isin(not_in_500)]

      SUBJ_ID BRND_CD BRND_CD_panel
86   S003-001     NaN          P021
88   S003-003     NaN          P035
89   S003-004     NaN          P034
93   S003-008     NaN          P034
95   S003-010     NaN          P034
96   S003-011     NaN          P035
100  S003-015     NaN          P034
110  S003-026     NaN          P034
120  S003-037     NaN          P034
121  S003-038     NaN          P021
122  S003-039     NaN          P034
123  S003-040     NaN          P033
125  S003-042     NaN          P034
138  S003-058     NaN          P034
148  S003-073     NaN          P034
149  S003-074     NaN          P034
159  S003-088     NaN          P034
170  S003-101     NaN          P034
173  S003-901     NaN          P034
221  S005-010     NaN          P025
236  S006-003     NaN          P032
243  S006-011     NaN          P032
250  S006-018     NaN          P032
251  S006-019     NaN          P032
254  S006-025     NaN          P032
265  S006-036     NaN          P032
271  S006-043     NaN          P032
279  S006-051     NaN          P032
283  S006-056     NaN          P032
303  S006-076     NaN          P032
304  S006-077     NaN          P032
333  S006-108     NaN          P032
367  S009-003     NaN          P003
369  S009-010     NaN          P003
371  S009-015     NaN          P034
372  S009-016     NaN          P003
420  S010-055     NaN          P003
449  S010-087     NaN          P036
454  S011-004     NaN          P002
458  S011-010     NaN          P002
473  S011-030     NaN          P021
496  S012-028     NaN          P036
497  S012-029     NaN          P036
498  S012-030     NaN          P036
503  S012-036     NaN          P036
507  S012-041     NaN          P036
517  S013-004     NaN          P034
530  S014-005     NaN          P014
531  S014-006     NaN          P014
534  S014-009     NaN          P014
587  S018-014     NaN          P031
590  S018-017     NaN          P030
646  S024-013     NaN          P031
659  S025-005     NaN          P034
695  S031-003     NaN          P034
704  S031-016     NaN          P034